theme = "dark_high_contrast"

[editor]
bufferline = "always"
cursorline = true
line-number = "relative"
end-of-line-diagnostics = "hint"
clipboard-provider = "tmux"
default-yank-register = "+"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
C-s = ":w"
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
C-c = [':sh claude -p "%{selection}"']
X = ":buffer-close"
C-x = ":q!"
C-g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]
C-z = ":config-reload"


[editor.inline-diagnostics]
cursor-line = "warning"


[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
